import test

if __name__ == '__main__':
    dna = "TGGTGTATGAGCTACCAGCCGTGCGAAACTCATACTATTATCTAATCAGGGACAATACCTCAGGCAGGACTGTGCTGTGTAGATAGCTGGAGAGTATTTCTGATTGTC" \
          "TCCGAGGGGTGTAAAGGTACTTGCAAGGCCACTCAACTCATGCAGCGTTTCCATTTGAGTTGCCTTGAGTAAACGTCAACGCAGCTGGGAGTAGTACCTCTTGGAGGT" \
          "TGTGACCGCCGCTGCCCGCATGGACAGACGCACGGAAATGTATTAACACTAACTATACT"

    print(test.test(dna, 20, 7))
